### ISSUE TITLE
Host docsify on GitHub and ensure it runs

### ISSUE THREAD

**Issue by TimKozak** [Sifchain/sa-eliza#152]
# 📚 Sa-Eliza Documentation Setup & Deployment Guide

## 🔍 Overview

**Sa-Eliza** is a documentation project powered by **Docsify**, a simple yet powerful tool that turns markdown files into beautiful, live documentation websites. This project leverages Docsify's dynamic capabilities, allowing real-time updates to the sidebar and content without manually rebuilding static files.

---

## 🚀 Why Docsify?
- **Dynamic Loading** – No need to generate static HTML, Docsify loads markdown files directly.
- **Simple Structure** – Just markdown files in a folder (`docs/`), no complex build processes.
- **Live Sidebar** – Sidebar (`_sidebar.md`) dynamically links to existing files.
- **Customizable** – Easy to style and configure.

> **Goal:** Automate sidebar generation, ensure documentation updates seamlessly, and deploy it to GitHub Pages.

---

## 📂 Project Structure
```
/sa-eliza
│
├── docs/                   # Markdown files for documentation
├── node_modules/           # Node.js dependencies
├── rs-documentation/       # Additional docs (optional)
│
├── generate-sidebar.js     # Script to auto-generate _sidebar.md
├── package.json            # npm configuration (scripts & dependencies)
├── package-lock.json       # Lock file for exact dependency versions
│
└── .github/workflows/      # GitHub Actions for automation
    └── generate-sidebar.yml
```

---

### 1. 📥 Environment Setup
1. **Clone the Repo:**
   ```bash
   git clone <sa-eliza-repo-url>
   cd sa-eliza
   ```
2. **Ensure Node.js and npm are Installed:**
   ```bash
   node -v
   npm -v
   ```
   If not installed, download Node.js from [https://nodejs.org/](https://nodejs.org/).

3. **Install Docsify CLI:**
   ```bash
   npm install -g docsify-cli
   ```

---

### 2. 📦 Install Project Dependencies
```bash
npm install
```
Ensure the following dependencies are listed in `package.json`:
```json
"dependencies": {
  "fs-extra": "^11.1.1",
  "path": "^0.12.7"
},
"devDependencies": {
  "nodemon": "^3.0.1"
}
```
If missing:
```bash
npm install fs-extra path nodemon --save-dev
```

---

### 3. 🛠️ Sidebar Generation

1. **Run the Sidebar Generation Script:**
   ```bash
   npm run generate:sidebar
   ```
   This will regenerate `_sidebar.md` inside the `docs/` folder.

2. **Serve Documentation Locally:**
   ```bash
   npm run serve
   ```
   Visit `http://localhost:3000` to preview the documentation.

3. **Auto-update on File Change:**
   ```bash
   npm run watch:sidebar
   ```
   This watches for changes in markdown files and regenerates the sidebar in real-time.

---

### 4. 🔄 Automate Sidebar Updates (GitHub Actions)

1. Ensure the following GitHub Action exists at `.github/workflows/generate-sidebar.yml`:
```yaml
name: Generate Sidebar

on:
  push:
    paths:
      - 'docs/**/*.md'
      - 'generate-sidebar.js'
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Generate Sidebar
      run: npm run generate:sidebar

    - name: Commit Changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add docs/_sidebar.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Automated Sidebar Update [skip ci]"
        git push
```

2. **Push Changes to Trigger the GitHub Action:**
   ```bash
   git add .
   git commit -m "Add sidebar generation action"
   git push
   ```

---

### 5. 🌐 Deploy to GitHub Pages
1. Go to the **sa-eliza** repo on GitHub.
2. Navigate to **Settings → Pages**.
3. Under "Branch," select `main` (or `master`) and `/docs` as the source.
4. Save and wait for deployment.
5. Access the live documentation at:
   ```
   https://<username>.github.io/sa-eliza
   ```

---

## ✅ Testing & Verification
- Add a new markdown file to `docs/` (e.g., `docs/new-feature.md`).

- Run the sidebar generation script:
   ```bash
   npm run generate:sidebar
   ```
- Confirm that `_sidebar.md` includes the new file.
- Push to GitHub and verify the site updates.

---

## 🚀 Final Notes
- **Docsify** dynamically loads markdown files, making it lightweight and fast.
- **GitHub Actions** automate sidebar updates, ensuring the site reflects the latest documentation without manual intervention.
- **Node.js** dependencies (`fs-extra`, `path`) handle file operations, and `nodemon` automates real-time sidebar updates during development.

Let me know if you have any questions or run into issues during setup!
